### ISSUE TITLE
Nullable user field in docs?

### ISSUE THREAD

**Issue by lamby** [jaylett/django_session_stashable#7]
https://github.com/jaylett/django_session_stashable/blob/master/README#L20

Shouldn't the User be nullable there? (Or am I missing something?)

**Comment by lamby** [comment]
Better late than never... see https://github.com/jaylett/django_session_stashable/pull/8

**Comment by jaylett** [comment]
I can't help feeling there's probably a better way of doing all this that I simply wasn't aware of… 10 years ago ;)

**Comment by lamby** [comment]
In*deed*. <grin>
